name: Build LaTeX document to HTML
on: [push]
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            make4ht -u -d out main.tex
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # The folder the action should deploy.
