name: Build LaTeX document to HTML
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/small@v1
        with:
          run: |
            apk add make4ht
            make4ht -u main.tex
      - name: Upload HTML file
        uses: actions/upload-artifact@v3
        with:
          name: HTML
          path: main.html
